## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap

install:
  - sudo apt-get install libv8-dev  # for V8 package, for spocc 
  - ./pkg-build.sh install_deps
  - ./pkg-build.sh install_r covr  # for coverage stats

script:
  - ./pkg-build.sh run_tests

# get code coverage stats for codecov
after_success:
 - Rscript -e 'library(covr);codecov()'

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    recipients:
      - zoonproject@gmail.com
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel

