# basic bits:
language: r
sudo: required

# R packages not listed in DESCRIPTION, but required for running the tests
# (i.e. because modules depend on them)

# these ones have linux binaries available at: https://launchpad.net/~marutter/+archive/ubuntu/c2d4u/ 
# so they can be loaded much more quickly
#r_binary_packages:
# - spocc
# - SDMTools
# - RNCEP
# - rfigshare
# - randomForest
# - mgcv
# - htmlwidgets

# these will be built from source, which takes longer
r_packages:
 - biomod2
 - leaflet
 - viridis
 - GRaF
 - sperrorest
 - rgbif
 - V8
 - spocc
 - SDMTools
 - RNCEP
 - rfigshare
 - randomForest
 - mgcv
 - htmlwidgets

