# basic bits:
language: r
sudo: required

# linux system dependencies for R packages
apt_packages:
 - libv8-dev  # for V8 package, for spocc

r_packages:
 - covr  # for code test coverage stats
 - devtools # for checking

script:
 - R CMD build .  # build
 - FILE=$(ls -1t *.tar.gz | head -n 1)  # find the tarball
 - R CMD check --as-cran --no-tests "${FILE}" # check as cran, without tests
 - R CMD install "${FILE}"  # install the tarball
 - Rscript -e "testthat::test_dir('tests')"  # run tests

# get code covarage stats for coveralls
after_success:
 - Rscript -e 'covr::coveralls()'

notifications:
  email:
    recipients:
      - zoonproject@gmail.com
    on_success: change
    on_failure: change
