# basic bits:
language: r
sudo: required

# R packages not listed in DESCRIPTION, but required for running the tests
# (i.e. because modules depend on them)

# heinous workaround for the gdal ubuntu bug discussed here:
# https://github.com/travis-ci/travis-ci/issues/2683
# and many other places
before_install:
# - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
# - sudo apt-get remove -y libgdal1
# - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
# - sudo apt-get update -y
# - sudo apt-get install -y libgdal1-dev libgdal-dev libgeos-c1=3.3.3-1.1 libspatialite3=3.1.0~rc2-1ubuntu1

# linux system dependencies for R packages
apt_packages:
# - libnetcdf-dev
# - netcdf-bin
# - libproj-dev
# - libgeos-dev
 - libv8-dev  # for V8 package, for spocc

# these ones have linux binaries available at: https://launchpad.net/~marutter/+archive/ubuntu/c2d4u/ 
# so they can be loaded much more quickly
r_binary_packages:
# - rgdal
# - rgeos
# - SDMTools
# - RNCEP
# - rfigshare
# - randomForest
# - mgcv
# - htmlwidgets

# these will be built from source, which takes longer
r_packages:
# - rgdal  # although there is a binary for it, a problem with gdal means we must build from source
# - rgbif  # and as rgbif ...
# - spocc  # ... and spocc rely on rgdal, we have to build these from source too 
# - biomod2
# - leaflet
# - viridis
# - GRaF
# - sperrorest
# - V8
 - covr  # for code test coverage stats

before_script:
 - R CMD build ../zoon
 - Rscript -e "library('zoon');testthat::test_check('zoon')"

# get code covarage stats for coveralls
after_success:
 - Rscript -e 'covr::coveralls()'
