# basic bits:
language: r
sudo: required

# linux system dependencies for R packages
apt_packages:
 - libv8-dev  # for V8 package, for spocc

r_packages:
 - covr  # for code test coverage stats

# get correct R version (adapted from metacran/r-builder)
before_install:
 - if [ "$RVERSION" == "release" ]; then RVERSION=$(wget -qO- "http://rversions.r-pkg.org/r-${RVERSION}" | grep version | tail -1 | cut -f2 -d: | tr -d '", '); fi
 - PATH="$HOME/R-bin/R-${RVERSION}/bin:${PATH}:/usr/texbin" # set the R version to be used

# bespoke script to get around R CMD check/testthat integration bug
script:
 - R CMD build .  # build
 - FILE=$(ls -1t *.tar.gz | head -n 1)  # find the tarball
 - R CMD check --as-cran --no-tests "${FILE}" # check as cran, without tests
 - Rscript -e "install.packages(list.files(pattern = '*.tar.gz$'), type = 'source', repos = NULL)"  # install package
 - Rscript -e "library(testthat);test_dir('tests')" # test it, from inside R

# get code coverage stats for codecov
after_success:
 - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    recipients:
      - zoonproject@gmail.com
    on_success: change  # only email when the status changes
    on_failure: change

# run this with release and devel versions of R
env:
  matrix:
    - RVERSION=release
    - RVERSION=devel
